name: Build & Deploy

on:
  push:
    branches:
      - feature/webpack_dist

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.0.0
    - name: Setup Node version 10.x
      uses: actions/setup-node@v1.1.0
      with:
        node-version: '10.x'
    - name: Yarn install, webpacking
      run: |
        yarn install --ignore-scripts
        yarn webpack:deploy
    - name: echo test
      run: |
        cd entry-hw
        ls -al
        cd scripts
        ls -al

